export const filmCards = [
    {
        id: 1,
        title: 'Айдар',
        category: 'Телехикая, Мультсериал',
        type: 'Мультфильм',
        rating: 8.5,
        yearProduced: 2021,
        addedToProjects: '21-05-2021',
        lastModified: '15-04-2024',
        viewsCount: 15201,
        duration: 10, // in minutes
        ageCategory: ['6-8', '8-10'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Сказка', 'Мульт','Супергерой'],
        thumbnail: 'cardImage1.png',
        seasons: [4],
    },
    {
        id: 2,
        title: 'Суперкөлік Самұрық',
        category: 'Телехикая, Мультсериал',
        type: 'Сериал',
        rating: 8.7,
        yearProduced: 2020,
        addedToProjects: '07-09-2020',
        lastModified: '22-01-2022',
        viewsCount: 10329,
        duration: 7, // in minutes
        ageCategory: ['8-10', '10-12'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Тачка', 'Мульт','Авто'],
        thumbnail: 'cardImage5.png',
        seasons: [12],
    },
    {
        id: 3,
        title: 'Каникулы off-line 2',
        category: 'Телехикая',
        type: 'Фильм',
        rating: 7.3,
        yearProduced: 2022,
        addedToProjects: '15-01-2022',
        lastModified: '30-01-2022',
        viewsCount: 9659,
        duration: 85, // in minutes
        ageCategory: ['12-16', '16+'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Дети', 'Кино','Каникулы', 'Ауыл'],
        thumbnail: 'cardImage6.png',
        seasons: [],
    },
    {
        id: 4,
        title: 'Ойыншықтар',
        category: 'Телехикая',
        type: 'Мультфильм',
        rating: 6.7,
        yearProduced: 2022,
        addedToProjects: '06-07-2023',
        lastModified: '11-08-2024',
        viewsCount: 9659,
        duration: 35, // in minutes
        ageCategory: ['4-6', '6-8'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Игрушки', 'Мульт','Куклы'],
        thumbnail: 'cardImage8.png',
        seasons: [],
    },
    {
        id: 5,
        title: 'Айдар',
        category: 'Телехикая, Мультсериал',
        type: 'Мультфильм',
        rating: 8.5,
        yearProduced: 2021,
        addedToProjects: '21-05-2021',
        lastModified: '15-04-2024',
        viewsCount: 15201,
        duration: 10, // in minutes
        ageCategory: ['6-8', '8-10'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Сказка', 'Мульт','Супергерой'],
        thumbnail: 'cardImage1.png',
        seasons: [4],
    },
    {
        id: 6,
        title: 'Ойыншықтар',
        category: 'Телехикая',
        type: 'Мультфильм',
        rating: 6.7,
        yearProduced: 2022,
        addedToProjects: '06-07-2023',
        lastModified: '11-08-2024',
        viewsCount: 9659,
        duration: 35, // in minutes
        ageCategory: ['4-6', '6-8'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Игрушки', 'Мульт','Куклы'],
        thumbnail: 'cardImage8.png',
        seasons: [],
    },
    {
        id: 7,
        title: 'Суперкөлік Самұрық',
        category: 'Телехикая, Мультсериал',
        type: 'Сериал',
        rating: 8.7,
        yearProduced: 2020,
        addedToProjects: '07-09-2020',
        lastModified: '22-01-2022',
        viewsCount: 10329,
        duration: 7, // in minutes
        ageCategory: ['8-10', '10-12'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Тачка', 'Мульт','Авто'],
        thumbnail: 'cardImage5.png',
        seasons: [12],
    },
    {
        id: 8,
        title: 'Каникулы off-line 2',
        category: 'Телехикая',
        type: 'Фильм',
        rating: 7.3,
        yearProduced: 2022,
        addedToProjects: '15-01-2022',
        lastModified: '30-01-2022',
        viewsCount: 9659,
        duration: 85, // in minutes
        ageCategory: ['12-16', '16+'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Дети', 'Кино','Каникулы', 'Ауыл'],
        thumbnail: 'cardImage6.png',
        seasons: [],
    },
    {
        id: 9,
        title: 'Айдар',
        category: 'Телехикая, Мультсериал',
        type: 'Мультфильм',
        rating: 8.5,
        yearProduced: 2021,
        addedToProjects: '21-05-2021',
        lastModified: '15-04-2024',
        viewsCount: 15201,
        duration: 10, // in minutes
        ageCategory: ['6-8', '8-10'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Сказка', 'Мульт','Супергерой'],
        thumbnail: 'cardImage1.png',
        seasons: [4],
    },
    {
        id: 10,
        title: 'Ойыншықтар',
        category: 'Телехикая',
        type: 'Мультфильм',
        rating: 6.7,
        yearProduced: 2022,
        addedToProjects: '06-07-2023',
        lastModified: '11-08-2024',
        viewsCount: 9659,
        duration: 35, // in minutes
        ageCategory: ['4-6', '6-8'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Игрушки', 'Мульт','Куклы'],
        thumbnail: 'cardImage8.png',
        seasons: [],
    },
    {
        id: 11,
        title: 'Суперкөлік Самұрық',
        category: 'Телехикая, Мультсериал',
        type: 'Сериал',
        rating: 8.7,
        yearProduced: 2020,
        addedToProjects: '07-09-2020',
        lastModified: '22-01-2022',
        viewsCount: 10329,
        duration: 7, // in minutes
        ageCategory: ['8-10', '10-12'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Тачка', 'Мульт','Авто'],
        thumbnail: 'cardImage5.png',
        seasons: [12],
    },
    {
        id: 12,
        title: 'Каникулы off-line 2',
        category: 'Телехикая',
        type: 'Фильм',
        rating: 7.3,
        yearProduced: 2022,
        addedToProjects: '15-01-2022',
        lastModified: '30-01-2022',
        viewsCount: 9659,
        duration: 85, // in minutes
        ageCategory: ['12-16', '16+'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Дети', 'Кино','Каникулы', 'Ауыл'],
        thumbnail: 'cardImage6.png',
        seasons: [],
    },
    {
        id: 13,
        title: 'Айдар',
        category: 'Телехикая, Мультсериал',
        type: 'Мультфильм',
        rating: 8.5,
        yearProduced: 2021,
        addedToProjects: '21-05-2021',
        lastModified: '15-04-2024',
        viewsCount: 15201,
        duration: 10, // in minutes
        ageCategory: ['6-8', '8-10'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Сказка', 'Мульт','Супергерой'],
        thumbnail: 'cardImage1.png',
        seasons: [4],
    },
    {
        id: 14,
        title: 'Ойыншықтар',
        category: 'Телехикая',
        type: 'Мультфильм',
        rating: 6.7,
        yearProduced: 2022,
        addedToProjects: '06-07-2023',
        lastModified: '11-08-2024',
        viewsCount: 9659,
        duration: 35, // in minutes
        ageCategory: ['4-6', '6-8'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Игрушки', 'Мульт','Куклы'],
        thumbnail: 'cardImage8.png',
        seasons: [],
    },
    {
        id: 15,
        title: 'Суперкөлік Самұрық',
        category: 'Телехикая, Мультсериал',
        type: 'Сериал',
        rating: 8.7,
        yearProduced: 2020,
        addedToProjects: '07-09-2020',
        lastModified: '22-01-2022',
        viewsCount: 10329,
        duration: 7, // in minutes
        ageCategory: ['8-10', '10-12'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Тачка', 'Мульт','Авто'],
        thumbnail: 'cardImage5.png',
        seasons: [12],
    },
    {
        id: 16,
        title: 'Каникулы off-line 2',
        category: 'Телехикая',
        type: 'Фильм',
        rating: 7.3,
        yearProduced: 2022,
        addedToProjects: '15-01-2022',
        lastModified: '30-01-2022',
        viewsCount: 9659,
        duration: 85, // in minutes
        ageCategory: ['12-16', '16+'],
        director: 'Бақдәулет Әлімбеков',
        producer: 'Сандуғаш Кенжебаева',
        keyTags: ['Дети', 'Кино','Каникулы', 'Ауыл'],
        thumbnail: 'cardImage6.png',
        seasons: [],
    },
]